### ISSUE TITLE
collapse ist unschön

### ISSUE THREAD

**Issue by mritzmann** [mritzmann/markusritzmann.ch#3]
to reproduce
1. Open `E-Mail`
2. Open `Adresse`

Die Infos von `E-Mail` bleiben, die Infos von `Adresse` werden desshalb weiter unten angezeigt. Auf einem Desktop Rechner mag das erkennbar sein. Auf einem Smartphone geht die Information jedoch unter.

Eine neue `collapse` sollte die alte schliessen.

**Comment by mritzmann** [comment]
Hat eventuell etwas mit dem fehlenden `data-parent="#accordion"` zu tun.

**Comment by heubergen** [comment]
Kein Collapse mit getestetem Gerät (Mozilla/5.0 (iPad; CPU OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1)

**Comment by mritzmann** [comment]
Hat sich mit dem neuen CSS Framework erledigt. a199226650f9f1ded6f70d77161a110bb1145942
