### ISSUE TITLE
dnszensur.ch : Server Not Found error

### ISSUE THREAD

**Issue by heubergen** [mritzmann/markusritzmann.ch#36]
Either replace the link with the internet archive version (https://web.archive.org/web/20190120213813/https://dnszensur.ch/) like you did with ueberwacht.ch or remove it completely.

**Comment by mritzmann** [comment]
Thanks for the reminder! I hope that the project will be [revived this year](https://twitter.com/DNSzensur/status/1232566128809037824). That's why I leave the broken link there, as motivation to move forward.
